name: weatherapp_with_flutterhooks
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Bold.otf
        - asset: assets/fonts/Geist/Geist-Regular.otf
        - asset: assets/fonts/Geist/Geist-SemiBold.otf
